defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: ouroboros

test:
  <<: *defaults
  database: milkman_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGODB_URL'] %>
